package com.berlski.tool.custom.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.berlski.tool.custom.dao.bean.Dictionary;
import com.berlski.tool.custom.dao.bean.Location;

import com.berlski.tool.custom.dao.DictionaryDao;
import com.berlski.tool.custom.dao.LocationDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig dictionaryDaoConfig;
    private final DaoConfig locationDaoConfig;

    private final DictionaryDao dictionaryDao;
    private final LocationDao locationDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        dictionaryDaoConfig = daoConfigMap.get(DictionaryDao.class).clone();
        dictionaryDaoConfig.initIdentityScope(type);

        locationDaoConfig = daoConfigMap.get(LocationDao.class).clone();
        locationDaoConfig.initIdentityScope(type);

        dictionaryDao = new DictionaryDao(dictionaryDaoConfig, this);
        locationDao = new LocationDao(locationDaoConfig, this);

        registerDao(Dictionary.class, dictionaryDao);
        registerDao(Location.class, locationDao);
    }
    
    public void clear() {
        dictionaryDaoConfig.clearIdentityScope();
        locationDaoConfig.clearIdentityScope();
    }

    public DictionaryDao getDictionaryDao() {
        return dictionaryDao;
    }

    public LocationDao getLocationDao() {
        return locationDao;
    }

}
